version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.12.0
    - 2.14.1
    - 2.14.2
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.12.0
    - 2.13.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-source-graphql
    versions:
    - 2.13.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
